window.gameContent.items = [
  { actionId: 'backButton',
    action: 'nothing',
    image: 'xd',
    name: 'Voltar',
    details: 'Fecha o inventário',
  },
  {
    actionId: 'bike',
    action: 'history',
    image: 'motoZ900.png',
    name: 'Kawasaki Ninja Z900',
    details: 'Moto das entregas. <br><br> Ou dos rolês da vida...',
  },
  { actionId: 'gear', name: 'Pager', type: 'history' },
  {
    actionId: 'gas1',
    action: 'changeStatus',
    image: 'gas1.png',
    name: 'Galão de Gasolina',
    details: 'Galão pequeno de gasolina, carrega 10l de combustível.<br><br> Bora pra mais uma corrida!',
    type: 'gas',
    value: 10,
  },
  {
    actionId: 'taw',
    image: 'gas1.png',
    name: 'Item teste 02',
    action: 'changeStatus',
    type: 'xp',
    value: 30,
    details: 'É o teste do XP.',
  },
];
